---
  - hosts: all
    gather_facts: yes
    post_tasks:
      - name: Ensure pip and pip3 are installed
        become: yes
        package:
          name: "{{item}}"
          state: present
        with_items:
          - python-pip
          - python3-pip
      - name: Upgrade pip before installing any other packages
        become: yes
        pip:
          name: "pip"
          version: "9.0.1"
      - name: Upgrade pip3 before installing any other packages
        become: yes
        pip:
          executable: pip3
          name: "pip"
          version: "9.0.1"
      - name: Install pip packages
        become: yes
        pip:
          name: "{{item.name}}"
          version: "{{item.version}}"
        with_items:
          - { name: 'cookiecutter', version: '1.6.0' }
          - { name: 'sqlparse', version: '0.2.4' }
      - name: Initialize Oracle SQL Developer
        copy:
          dest: /home/vagrant/.sqldeveloper/17.4.1/
          group: vagrant
          mode: 0664
          owner: vagrant
          src: files/.sqldeveloper/product.conf
    roles:
      - role: ferrarimarco.atom
        become: yes
        ferrarimarco_atom_become_users:
          - username: ferrarimarco
            atom_packages:
              - atom-beautify
              - autocomplete-plus
              - autocomplete-python
              - busy-signal
              - color-picker
              - file-icons
              - hyperclick
              - intentions
              - language-ansible
              - language-docker
              - language-powershell
              - linter
              - linter-ui-default
              - minimap
              - pigments
              - sort-lines
        ferrarimarco_atom_atom_version: "1.25.0"
      - role: ferrarimarco.vagrant
        become: yes
        vagrant_download_url: "https://releases.hashicorp.com/vagrant/2.0.3/vagrant_2.0.3_x86_64.deb"
      - role: ferrarimarco.oracle-sql-developer
        become: yes
        ferrarimarco_oracle_sql_dev_archive_path: "/tmp/sqldeveloper-no-jre.zip"
      - role: chrisevett.inspec
        become: yes
        inspecVersion: "2.0.45"
      - role: geerlingguy.ansible-role-packer
        become: yes
        packer_version: "1.2.1"
