---
dependencies: []

galaxy_info:
  author: ferrarimarco
  description: Setup a development box
  license: "license (Apache 2.0)"
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
      - trusty
      - xenial
  galaxy_tags:
    - development
    - installer
